name: Build Container
on:
  push:
    branches:
      - master
env:
  IMAGE_NAME: ${{ secrets.DOCKER_IMAGE }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@master

      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build and Push
        run: |
          docker build -t $IMAGE_NAME:${{ github.sha }} -t $IMAGE_NAME:latest ./src
          docker push $IMAGE_NAME:${{ github.sha }}
          docker push $IMAGE_NAME:latest